### ISSUE TITLE
Sign Up button broken?

### ISSUE THREAD

**Issue by domiflichi** [0perationPrivacy/VoIP#160]
There seems to be an issue with the 'Sign Up' button. When I enter a new username and password (twice), click on the blue 'Sign Up' button, absolutely nothing happens. I've tried it on Firefox, Chrome, and Brave, all with the same issue. 
Just to be clear where I'm at - I've followed the instructions at: https://inteltechniques.com/voip.suite.html to the point just after doing all the MongoDB stuff.
So I am at the part where I go to my new URL: https://voipsuite-XXXX.onrender.com/voip/signup to create a new account. I tried entering nothing into the fields and then clicking on the Sign Up button to see if it would at least throw an error, but it did not. It's like the button is just dead.

**Comment by 0perationPrivacy** [comment]
Check your environment variables. It's likely the DB url that's incorrect.
Password is without the brackets and no special characters.

**Comment by domiflichi** [comment]
Well, you're right - my connection string had extra text at the beginning. However, I fixed it, saved it, and tried again, but same problem. Here's my sanitized connection string:
mongodb+srv://mymongodbuser:mymongodbpassword>@cluster0.x2xuneh.mongodb.net/test

I downloaded Mongo's MongoDB Compass and used my MongoDB connection string and it connected just fine, so it seems the string (which includes the username and password of course) are all correct, and the database is set up properly.

At some point while playing around back on the web app, I noticed the URL changed to:
https://voipsuite-19xk.onrender.com/undefined/signup
Does that 'undefined' give any clues as to what's going on? (Seems like a Javascript issue?). 
<Holy crap...just as I finished typing the above/last sentence, I remembered that I have Adblock Plus and uBlock Origin on my main browser (Firefox)...the whole possible Javascript triggered this thought>

Soooo, I guess my problem was two-fold - 1. A bad db connection string as you suggested, and 2. A naughty browser plug-in!
Thank you for your help! I don't know how long it would've taken me to think to double-check the connection string.
And thank you for this project!

Time to continue with the set up...

**Comment by 0perationPrivacy** [comment]
I still see a `>` in your connection string above, maybe it's a typo here, but it shouldn't be in the actual string.
Also uBlock shoud not affect anything, I have it on, it works fine with it. I don't use AdBlock plus but that shouldn't matter either. There are no external calls that can get blocked. 99% of issues are to do with the environment variable strings, passwords, base_url, etc.

**Comment by domiflichi** [comment]
Oops, yup, definitely a typo here.
That's really strange. Because even after I fixed the connection string, it still didn't work. But after I turned off Adblock Plus and uBlock Origin, it worked. Now, technically there were 'refreshes' involved after turning off each plug-in...maybe that was part of it? But that would be strange though, because everytime I tried something new, I actually closed the tab, then re-opened it so I would've thought that that would've been 'enough'.

**Comment by 0perationPrivacy** [comment]
i would say try it on the publicly hosted version with the same browser settings, uBlock Origin and AdBlock turned on. https://voip.operationprivacy.com 

If the result is the same, then it may be the plugin. I can tell I have firefox and ublock on and it works fine.
If one works and the other doesn't, then it's your env variables, something isn't typed in right.

**Comment by domiflichi** [comment]
Well that was interesting...the 'Sign Up' button did something, but it took me to:
https://voip.operationprivacy.com/404   (a black page with a white animated '404' in the middle)
So completely different results here. (I left Adblock Plus and uBlock Origin on as you instructed). Does it matter that I put in the same username (but a different password) as I signed up for on my own app/URL? 

Regardless, I just want to make sure that you saw the part in my post from an hour ago that my app **is** working now (after I fixed the string and turned off the 2 browser plugins) - I don't want you to waste your time thinking it's still not working for me. But if you want me to try these different things just for our curiosity, or for your reference, I am more than willing to do any tests you want. It's the least I can do.

**Comment by 0perationPrivacy** [comment]
The username password will be different as it's running a different instance of mongodb as your self-hosted version. So you'll need to signup with a new set of credentials.

Good to know it's working, but I was curious on if or why a plugin was interfering. Always try to hard refresh or test in private mode (as session cookies get saved in the browser for the particular url).

**Comment by domiflichi** [comment]
Yeah, that's what I was doing - the 'Sign Up' again. I figured it wouldn't matter if I used the same or different credentials as my self-hosted version, but just wanted to mention it just in case, especially since I got completely different results (the 404 error page).

Thank you for the tips. 

If there's anything that I can help you test, my email address is domiflichi at gmail dot com. Or anything else I can help out with - like documentation, or a video tutorial based on Michael's walkthrough on his site, or whatever - please let me know. Just say the word!

Jamie
